name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: home-assistant/actions/hassfest@master
